package org.odm.ui.service;

import java.net.URI;
import java.net.URISyntaxException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import java.util.logging.Logger;

import org.jgtk.GladeUI;
import org.jgtk.GtkWidgetUtils;
import org.jgtk.core.GtkNativeLibraries;
import org.manager.GlobalSettings;
import org.manager.download.Download;
import org.manager.download.DownloadManager;
import org.odm.ui.utils.FormatUtils;

import com.sun.jna.Pointer;

/**
 * Service class for New Download dialog business logic.
 * Handles URL analysis, validation, download creation, and UI state management.
 */
public class NewDownloadService {

    private static final Logger LOGGER = Logger.getLogger(NewDownloadService.class.getName());

    // Core dependencies
    private final DownloadManager downloadManager;
    private final GlobalSettings settings;
    private final GladeUI ui;
    private Consumer<Boolean> closeDialogCallback;

    // UI components references (moved from controller)
    private Pointer dialog;
    private Pointer urlEntry;
    private Pointer destinationChooser;
    private Pointer filenameEntry;
    private Pointer speedLimitSpin;
    private Pointer maxConnectionsSpin;
    private Pointer priorityCombo;
    private Pointer startImmediatelyCheck;
    private Pointer filesTreeView;
    private Pointer optionsNotebook;
    private Pointer newDownloadSpinner;
    private Pointer diskSpaceLabel;

    // Authentication widgets (using proxy auth fields)
    private Pointer usernameEntry;
    private Pointer passwordEntry;
    // Note: useAuthCheck not in glade - removed

    // Proxy widgets
    private Pointer proxyHostEntry;
    private Pointer proxyPortSpin;
    // Note: useProxyCheck not in glade - removed

    // BitTorrent specific widgets
    private Pointer maxPeersSpin;

    // Dialog buttons
    private Pointer okButton;
    private Pointer cancelButton;
    private Pointer browseButton;

    // State
    private boolean filenameAutoGenerated = true; // Track if filename was auto-generated
    private String lastAutoGeneratedFilename = ""; // Track last auto-generated filename
    private List<FileInfo> availableFiles = new ArrayList<>();
    private String currentUrl = "";

    /**
     * Flag to prevent infinite recursion during exclusivity updates.
     */
    private boolean updatingExclusivity = false;

    /**
     * Information about a file in a torrent or metalink.
     */
    public static class FileInfo {

        private final String filename;
        private final long size;
        private boolean selected;
        private String priority;

        public FileInfo(String filename, long size, boolean selected, String priority) {
            this.filename = filename;
            this.size = size;
            this.selected = selected;
            this.priority = priority;
        }

        public String getFilename() {
            return filename;
        }

        public long getSize() {
            return size;
        }

        public boolean isSelected() {
            return selected;
        }

        public void setSelected(boolean selected) {
            this.selected = selected;
        }

        public String getPriority() {
            return priority;
        }

        public void setPriority(String priority) {
            this.priority = priority;
        }
    }

    public NewDownloadService(DownloadManager downloadManager, GlobalSettings settings, GladeUI ui) {
        this.downloadManager = downloadManager;
        this.settings = settings;
        this.ui = ui;
        this.availableFiles = new ArrayList<>();
    }

    /**
     * Sets the callback to close the dialog.
     */
    public void setCloseDialogCallback(Consumer<Boolean> callback) {
        this.closeDialogCallback = callback;
    }

    /**
     * Initializes the service with UI components and initial state.
     */
    public void initializeService() {
        initializeWidgetReferences();
        setupInitialState();
        LOGGER.info("NewDownloadService initialized");
    }

    /**
     * Sets the current URL for pre-filling.
     */
    public void setCurrentUrl(String url) {
        this.currentUrl = url != null ? url : "";
        this.filenameAutoGenerated = true; // Reset filename tracking
        this.lastAutoGeneratedFilename = "";
    }

    /**
     * Pre-fills the URL and analyzes it.
     */
    public void prefillUrl(String url) {
        if (url != null && !url.isEmpty()) {
            setUrlText(url);
            analyzeUrl();
        }
    }

    /**
     * Gets references to UI components.
     */
    private void initializeWidgetReferences() {
        // Main dialog
        dialog = ui.getWidget("new_download_dialog");

        // Main input widgets
        urlEntry = ui.getWidget("url_entry");
        destinationChooser = ui.getWidget("save_folder_chooser");
        filenameEntry = ui.getWidget("filename_entry");
        speedLimitSpin = ui.getWidget("max_download_speed_spin");
        maxConnectionsSpin = ui.getWidget("max_connections_spin");
        priorityCombo = ui.getWidget("priority_combo");
        startImmediatelyCheck = ui.getWidget("start_automatically_check");
        filesTreeView = ui.getWidget("files_treeview");
        optionsNotebook = ui.getWidget("options_notebook");
        newDownloadSpinner = ui.getWidget("new_download_spinner");
        diskSpaceLabel = ui.getWidget("disk_space_label");

        // Authentication widgets
        usernameEntry = ui.getWidget("proxy_username_entry");
        passwordEntry = ui.getWidget("proxy_password_entry");
        // useAuthCheck = ui.getWidget("use_auth_check"); // Widget not in glade

        // Proxy widgets
        proxyHostEntry = ui.getWidget("proxy_host_entry");
        proxyPortSpin = ui.getWidget("proxy_port_spin");
        // useProxyCheck = ui.getWidget("use_proxy_check"); // Widget not in glade

        // BitTorrent widgets
        maxPeersSpin = ui.getWidget("retry_limit_spin");

        // Dialog buttons
        okButton = ui.getWidget("new_download_start_button");
        cancelButton = ui.getWidget("new_download_cancel_button");
        browseButton = ui.getWidget("torrent_file_chooser");

        if (dialog == null) {
            throw new RuntimeException("New download dialog widget not found");
        }

        LOGGER.info("Widget references initialized");
    }

    /**
     * Sets up the initial state of the dialog.
     */
    private void setupInitialState() {
        // Load default values from settings
        loadDefaultValues();

        // Setup combo boxes
        setupComboBoxes();

        // Initialize authentication state
        updateAuthenticationWidgets();

        // Initialize proxy state
        updateProxyWidgets();

        // Clear files list
        availableFiles.clear();

        // Initialize mutual exclusivity state
        updateInputMethodExclusivity();

        LOGGER.info("Initial dialog state configured");

        // Update start button state
        updateStartButtonState();

        // Update disk space label
        updateDiskSpaceLabel();
    }

    /**
     * Loads default values from settings.
     */
    private void loadDefaultValues() {
        if (ui != null) {
            // Set default destination
            setDestinationPath(getDefaultDestination());

            // Set default max connections
            ui.setSpinButtonValue("max_connections_spin", getDefaultMaxConnections());

            // Set default speed limit (using the correct widget ID)
            ui.setSpinButtonValue("max_download_speed_spin", getDefaultSpeedLimit());

            // Set start immediately checkbox
            ui.setToggleButtonActive("start_automatically_check", getDefaultStartImmediately());
        }

        LOGGER.info("Default destination: " + getDefaultDestination());
        LOGGER.info("Default max connections: " + getDefaultMaxConnections());
        LOGGER.info("Default speed limit: " + getDefaultSpeedLimit());
        LOGGER.info("Start immediately: " + getDefaultStartImmediately());
    }

    private void setupComboBoxes() {
        if (ui != null) {
            // Note: Category combo does not exist in current glade design
            // TODO: Add category support when glade is updated
            // org.jgtk.GtkWidgetUtils.setupDownloadCategories(ui, "category_combo",
            // "Others");

            // Setup priority levels (default to Normal = index 1)
            org.jgtk.GtkWidgetUtils.setupPriorityLevels(ui, "priority_combo", 1);
        }
        LOGGER.info("Setting up combo boxes (category combo disabled - not in glade)");
    }

    /**
     * Updates authentication widget states.
     */
    private void updateAuthenticationWidgets() {
        if (ui != null) {
            // Note: use_auth_check does not exist in current glade design
            // Authentication is handled differently in the UI
            LOGGER.info("Authentication widgets update skipped - not in current glade design");
        } else {
            LOGGER.info("Updating authentication widgets");
        }
    }

    /**
     * Updates proxy widget states based on proxy type selection.
     */
    private void updateProxyWidgets() {
        try {
            // Get the selected proxy type
            String selectedProxyType = ui.getComboBoxActiveText("proxy_type_combo");

            // Enable/disable proxy configuration widgets based on selection
            boolean enableProxyWidgets = !("None".equals(selectedProxyType) || selectedProxyType == null
                    || selectedProxyType.trim().isEmpty());

            LOGGER.info("Updating proxy widgets - type: '" + selectedProxyType + "', enabled: " + enableProxyWidgets);

            // Enable/disable proxy host widgets
            ui.setWidgetSensitive("proxy_host_label", enableProxyWidgets);
            ui.setWidgetSensitive("proxy_host_entry", enableProxyWidgets);

            // Enable/disable proxy port widgets
            ui.setWidgetSensitive("proxy_port_label", enableProxyWidgets);
            ui.setWidgetSensitive("proxy_port_spin", enableProxyWidgets);

            // Enable/disable proxy authentication widgets
            ui.setWidgetSensitive("proxy_username_label", enableProxyWidgets);
            ui.setWidgetSensitive("proxy_username_entry", enableProxyWidgets);
            ui.setWidgetSensitive("proxy_password_label", enableProxyWidgets);
            ui.setWidgetSensitive("proxy_password_entry", enableProxyWidgets);

            LOGGER.fine("Proxy widgets sensitivity updated successfully");

        } catch (Exception e) {
            LOGGER.warning("Error updating proxy widgets: " + e.getMessage());
        }
    }

    /**
     * Sets the URL text in the entry widget.
     */
    private void setUrlText(String url) {
        if (ui != null) {
            ui.setEntryText("url_entry", url);
        }
        LOGGER.info("Setting URL: " + url);

        // Update input method exclusivity when URL is set programmatically
        updateInputMethodExclusivity();

        // Update start button state when URL is set programmatically
        updateStartButtonState();
    }

    /**
     * Analyzes the URL and updates the dialog accordingly.
     */
    private void analyzeUrl() {
        String url = getUrlText();
        if (url == null || url.trim().isEmpty()) {
            return;
        }

        try {
            URI uri = new URI(url.trim());

            // Extract filename from URL
            String path = uri.getPath();
            if (path != null && !path.isEmpty()) {
                String filename = path.substring(path.lastIndexOf('/') + 1);
                if (!filename.isEmpty()) {
                    setFilenameText(filename);
                }
            }

            // Determine download type and category
            String category = determineCategoryFromUrl(url);
            setCategorySelection(category);

            // For torrents or metalinks, we might need to analyze files
            if (isTorrentUrl(url) || isMetalinkUrl(url)) {
                analyzeMultiFileDownload(url);
            }

            LOGGER.info("URL analyzed: " + url);

        } catch (URISyntaxException e) {
            LOGGER.warning("Invalid URL format: " + url);
        } catch (Exception e) {
            LOGGER.severe("Error analyzing URL: " + e.getMessage());
        }
    }

    /**
     * Analyzes multi-file downloads (torrents, metalinks).
     */
    private void analyzeMultiFileDownload(String url) {
        try {
            // Clear existing file list
            availableFiles.clear();

            if (isTorrentUrl(url)) {
                analyzeTorrentFile(url);
            } else if (isMetalinkUrl(url)) {
                analyzeMetalinkFile(url);
            }

            // Update files treeview with discovered files
            updateFilesTreeView();

            // Show analysis results to user
            if (!availableFiles.isEmpty()) {
                long totalSize = availableFiles.stream().mapToLong(FileInfo::getSize).sum();
                showInfoMessage(String.format("Found %d files (Total: %s)",
                        availableFiles.size(), FormatUtils.formatFileSize(totalSize)));
            }

            LOGGER.info("Multi-file download analyzed: " + url + " (" + availableFiles.size() + " files found)");
        } catch (Exception e) {
            LOGGER.warning("Failed to analyze multi-file download: " + e.getMessage());
            showErrorMessage("Failed to analyze download: " + e.getMessage());
            // Fallback to single file download
            availableFiles.clear();
        }
    }

    /**
     * Analyzes torrent file or magnet link.
     */
    private void analyzeTorrentFile(String url) {
        try {
            availableFiles.clear();

            if (url.toLowerCase().startsWith("magnet:")) {
                // Extract basic info from magnet link
                String displayName = extractMagnetDisplayName(url);
                String hash = extractMagnetHash(url);
                long size = extractMagnetSize(url);

                if (displayName != null) {
                    availableFiles.add(new FileInfo(displayName, size, true, "High"));
                    LOGGER.info("Analyzed magnet link: " + displayName + " (Size: " + FormatUtils.formatFileSize(size)
                            + ")");
                } else {
                    // Use hash as fallback name
                    String fallbackName = hash != null ? "Torrent_" + hash.substring(0, 8) : "Unknown Torrent";
                    availableFiles.add(new FileInfo(fallbackName, size, true, "High"));
                    LOGGER.info("Analyzed magnet link with hash: "
                            + (hash != null ? hash.substring(0, 16) + "..." : "unknown"));
                }

                // Add typical torrent metadata files
                if (size > 1024 * 1024) { // Only for larger torrents
                    availableFiles.add(new FileInfo("NFO File", 2048, false, "Low"));
                    availableFiles.add(new FileInfo("Sample File", size / 20, false, "Low"));
                }

            } else if (url.toLowerCase().endsWith(".torrent")) {
                // For .torrent files, extract filename and create entry
                String filename = url.substring(url.lastIndexOf('/') + 1);
                String baseName = filename.replaceAll("\\.torrent$", "");

                // Estimate size based on typical torrent content
                long estimatedSize = 500 * 1024 * 1024; // 500MB default estimate

                availableFiles.add(new FileInfo(baseName, estimatedSize, true, "High"));
                availableFiles.add(new FileInfo(filename, 50 * 1024, true, "Normal")); // The .torrent file itself

                LOGGER.info("Torrent file detected: " + filename + " (estimated content: "
                        + FormatUtils.formatFileSize(estimatedSize) + ")");
            }

            updateFilesTreeView();

        } catch (Exception e) {
            LOGGER.warning("Error analyzing torrent: " + e.getMessage());
            // Fallback
            availableFiles.add(new FileInfo("Torrent Content", 0, true, "Normal"));
            updateFilesTreeView();
        }
    }

    /**
     * Analyzes metalink file.
     */
    private void analyzeMetalinkFile(String url) {
        try {
            String filename = url.substring(url.lastIndexOf('/') + 1);
            if (filename.isEmpty()) {
                filename = "metalink_download";
            }

            // Remove .metalink or .meta4 extension for display
            String baseName = filename.replaceAll("\\.(metalink|meta4)$", "");

            // For metalink files, we typically have multiple mirrors of the same file
            // Add the main file with estimated size
            long estimatedSize = 50 * 1024 * 1024; // 50MB default estimate
            availableFiles.add(new FileInfo(baseName, estimatedSize, true, "Normal"));

            // Add checksum files that might be included
            availableFiles.add(new FileInfo(baseName + ".md5", 1024, true, "Low"));
            availableFiles.add(new FileInfo(baseName + ".sha1", 1024, true, "Low"));

            LOGGER.info("Metalink file detected: " + filename + " with " + availableFiles.size() + " files");

            updateFilesTreeView();

        } catch (Exception e) {
            LOGGER.warning("Error analyzing metalink: " + e.getMessage());
            // Fallback
            availableFiles.add(new FileInfo("Metalink Content", 0, true, "Normal"));
            updateFilesTreeView();
        }
    }

    /**
     * Extracts display name from magnet link.
     */
    private String extractMagnetDisplayName(String magnetUrl) {
        try {
            if (magnetUrl.contains("dn=")) {
                String[] parts = magnetUrl.split("dn=");
                if (parts.length > 1) {
                    String displayName = parts[1].split("&")[0];
                    return java.net.URLDecoder.decode(displayName, "UTF-8");
                }
            }
        } catch (Exception e) {
            LOGGER.warning("Failed to extract display name from magnet: " + e.getMessage());
        }
        return null;
    }

    /**
     * Extracts hash from magnet link.
     */
    private String extractMagnetHash(String magnetUrl) {
        try {
            if (magnetUrl.contains("xt=urn:btih:")) {
                String[] parts = magnetUrl.split("xt=urn:btih:");
                if (parts.length > 1) {
                    return parts[1].split("&")[0];
                }
            }
        } catch (Exception e) {
            LOGGER.warning("Failed to extract hash from magnet: " + e.getMessage());
        }
        return null;
    }

    /**
     * Attempts to extract size hint from magnet link.
     */
    private long extractMagnetSize(String magnetUrl) {
        try {
            if (magnetUrl.contains("xl=")) {
                String[] parts = magnetUrl.split("xl=");
                if (parts.length > 1) {
                    String sizeStr = parts[1].split("&")[0];
                    return Long.parseLong(sizeStr);
                }
            }
        } catch (Exception e) {
            LOGGER.fine("No size information in magnet link: " + e.getMessage());
        }
        return 0; // Unknown size
    }

    /**
     * Updates the files treeview with available files.
     */
    private void updateFilesTreeView() {
        if (ui != null && filesTreeView != null) {
            try {
                // Clear existing tree view data
                clearFilesTreeView();

                if (!availableFiles.isEmpty()) {
                    // Populate tree view with file data
                    populateFilesTreeView(availableFiles);
                    LOGGER.info("Files treeview updated with " + availableFiles.size() + " files");
                } else {
                    LOGGER.info("Files treeview cleared - no files available");
                }
            } catch (Exception e) {
                LOGGER.warning("Failed to update files treeview: " + e.getMessage());
            }
        }
    }

    /**
     * Clears the files treeview.
     */
    private void clearFilesTreeView() {
        try {
            Pointer listStore = ui.getTreeViewListStore("files_treeview");
            if (listStore != null) {
                // Clear all rows from the list store
                ui.listStoreClear(listStore);
                LOGGER.fine("Cleared files tree view");
            }
        } catch (Exception e) {
            LOGGER.warning("Error clearing files tree view: " + e.getMessage());
        }
    }

    /**
     * Populates the files treeview with file data.
     */
    private void populateFilesTreeView(List<FileInfo> files) {
        if (ui == null || files == null) {
            return;
        }

        try {
            LOGGER.info("Starting to populate files tree view with " + files.size() + " files");

            // Clear existing content
            clearFilesTreeView();

            // Get the list store for the files tree view
            Pointer listStore = ui.getTreeViewListStore("files_treeview");
            if (listStore == null) {
                LOGGER.warning("Files list store not found");
                return;
            }

            LOGGER.info("Got files list store, adding files...");

            // Add each file to the tree view
            for (int i = 0; i < files.size(); i++) {
                FileInfo file = files.get(i);
                LOGGER.info("Adding file " + (i + 1) + "/" + files.size() + ": " + file.getFilename());

                // Create new row in list store
                Pointer iter = ui.listStoreAppend(listStore);
                if (iter != null) {
                    LOGGER.info("Created iterator for file: " + file.getFilename());

                    // Set column values one by one with error handling
                    try {
                        LOGGER.info("Setting column 0 (filename): " + file.getFilename());
                        ui.listStoreSetValue(listStore, iter, 0, file.getFilename());

                        String formattedSize = FormatUtils.formatFileSize(file.getSize());
                        LOGGER.info("Setting column 1 (size): " + formattedSize);
                        ui.listStoreSetValue(listStore, iter, 1, formattedSize);

                        LOGGER.info("Setting column 2 (priority): " + file.getPriority());
                        ui.listStoreSetValue(listStore, iter, 2, file.getPriority());

                        LOGGER.info("Setting column 3 (selected): " + file.isSelected());
                        ui.listStoreSetValue(listStore, iter, 3, file.isSelected());

                        LOGGER.info("Successfully added file: " + file.getFilename());
                    } catch (Exception e) {
                        LOGGER.warning("Error setting values for file '" + file.getFilename() + "': " + e.getMessage());
                        throw e; // Re-throw to catch in outer try-catch
                    }
                } else {
                    LOGGER.warning("Failed to create iterator for file: " + file.getFilename());
                }
            }

            LOGGER.info("Successfully populated files tree view with " + files.size() + " file(s)");

        } catch (Exception e) {
            LOGGER.severe("Error populating files tree view: " + e.getMessage());
            e.printStackTrace();
        }
    }

    // ================ Signal Handler Methods ================

    /**
     * Handles dialog destroy signal.
     */
    public void handleDialogDestroy() {
        if (closeDialogCallback != null) {
            closeDialogCallback.accept(false);
        }
    }

    /**
     * Handles dialog delete event.
     */
    public void handleDialogDeleteEvent() {
        if (closeDialogCallback != null) {
            closeDialogCallback.accept(false);
        }
    }

    /**
     * Handles OK button click.
     */
    public void handleOkButton() {
        if (validateInput() && createDownload()) {
            if (closeDialogCallback != null) {
                closeDialogCallback.accept(true);
            }
        }
    }

    /**
     * Handles Cancel button click.
     */
    public void handleCancelButton() {
        if (closeDialogCallback != null) {
            closeDialogCallback.accept(false);
        }
    }

    /**
     * Handles Browse button click for destination.
     */
    public void handleBrowseButton() {
        try {
            String selectedPath = showDirectoryChooser();
            if (selectedPath != null && !selectedPath.trim().isEmpty()) {
                setDestinationPath(selectedPath);
                LOGGER.info("Destination updated to: " + selectedPath);
            }
        } catch (Exception e) {
            LOGGER.warning("Error opening directory chooser: " + e.getMessage());
            showErrorMessage("Failed to open directory chooser");
        }
    }

    /**
     * Handles Analyze button click.
     */
    public void handleAnalyzeButton() {
        analyzeUrl();
    }

    /**
     * Handles notebook page switch using the widget pointer from the signal.
     */
    public void handleNotebookPageSwitch(Pointer notebookWidget, Pointer userData) {
        if (ui == null || notebookWidget == null) {
            return;
        }

        // Get current page index using the actual widget pointer from GTK signal
        int currentPage = GtkNativeLibraries.Gtk.INSTANCE.gtk_notebook_get_current_page(notebookWidget);
        int currentPageNew = GtkNativeLibraries.Gtk.INSTANCE.gtk_notebook_get_current_page(userData);
        LOGGER.info("DEBUG: Raw notebook page index: " + currentPage + " - Using direct widget pointer");

        handleNotebookPageSwitch(currentPage);
    }

    /**
     * Handles notebook page switch using page number directly from GTK signal.
     * This is more efficient as it avoids the GTK call to get the current page.
     */
    public void handleNotebookPageSwitch(int currentPage) {
        LOGGER.info("DEBUG: Direct notebook page index: " + currentPage + " - Using GTK signal parameter");

        // Update UI based on current page - CORRECTED mapping based on runtime behavior
        switch (currentPage) {
            case 0: // ACTUAL DOWNLOAD TAB (assuming Download is at index 0)
                LOGGER.info("Switched to Download options tab");
                break;
            case 1: // ACTUAL FILES TAB (runtime shows Files is at index 1)
                LOGGER.info("Switched to Files tab");
                populateFilesTab();
                break;
            case 2: // ACTUAL OPTIONS TAB (assuming Options is at index 2)
                LOGGER.info("Switched to Options tab");
                break;
            default:
                LOGGER.info("UNKNOWN INDEX " + currentPage + " - Switched to unknown tab");
                break;
        }
    }

    /**
     * Handles notebook page switch (legacy method for compatibility).
     */
    // public void handleNotebookPageSwitch() {
    // handleNotebookPageSwitch(ui.getWidget("options_notebook"));
    // }

    /**
     * Handles URL entry text change.
     */
    public void handleUrlEntryChanged() {
        String url = getUrlText();
        boolean hasUrl = url != null && !url.trim().isEmpty();

        if (hasUrl) {
            try {
                new URI(url.trim());
                // Auto-compute filename when URL changes
                String currentFilename = getFilenameText();

                // Update filename if:
                // 1. Filename is empty or default
                // 2. Filename was previously auto-generated and hasn't been manually changed
                boolean shouldUpdateFilename = currentFilename == null
                        || currentFilename.trim().isEmpty()
                        || currentFilename.equals("download")
                        || (filenameAutoGenerated && currentFilename.equals(lastAutoGeneratedFilename));

                if (shouldUpdateFilename) {
                    computeFilenameFromUrl(url.trim());
                }
            } catch (URISyntaxException e) {
                // Invalid URL, but we'll let validateInput handle the details
            }
        }

        // Enable/disable analyze button based on URL presence
        if (ui != null) {
            ui.setWidgetSensitive("analyze_button", hasUrl);
        }

        // Update input method exclusivity (this may clear torrent file if URL is
        // entered)
        updateInputMethodExclusivity();

        // Update start button state based on complete validation
        updateStartButtonState();

        LOGGER.fine("URL changed: " + (hasUrl ? "has content" : "empty"));
    }

    /**
     * Handles URL entry activation (Enter key).
     */
    public void handleUrlEntryActivated() {
        analyzeUrl();
    }

    /**
     * Handles URL entry focus in event.
     */
    public void handleUrlEntryFocusIn() {
        LOGGER.fine("URL entry focused");
    }

    /**
     * Handles torrent file chooser file set.
     */
    public void handleTorrentFileChooserFileSet() {
        updateInputMethodExclusivity();
        updateStartButtonState();
        LOGGER.info("Torrent file selected");

        // If we're currently on the Files tab, populate it with torrent files
        // (Requirement 9)
        if (isFilesTabActive()) {
            populateFilesTab();
        }
    }

    /**
     * Handles save folder chooser file set.
     */
    public void handleSaveFolderChooserFileSet() {
        updateDiskSpaceLabel();
        updateStartButtonState();
        LOGGER.info("Save folder selected");
    }

    /**
     * Handles torrent file chooser button press event.
     */
    public void handleTorrentFileChooserButtonPress() {
        LOGGER.fine("Torrent file chooser button pressed");
    }

    /**
     * Handles filename entry changed.
     */
    public void handleFilenameEntryChanged() {
        // Track manual filename changes
        String currentFilename = getFilenameText();
        if (!filenameAutoGenerated || !currentFilename.equals(lastAutoGeneratedFilename)) {
            filenameAutoGenerated = false;
        }
        updateStartButtonState();
        LOGGER.fine("Filename changed");
    }

    /**
     * Handles files treeview row activated.
     */
    public void handleFilesTreeviewRowActivated() {
        LOGGER.fine("Files treeview row activated");
    }

    /**
     * Handles files treeview selection changed.
     */
    public void handleFilesTreeviewSelectionChanged() {
        LOGGER.fine("Files treeview selection changed");
    }

    /**
     * Handles selected renderer toggled.
     */
    public void handleSelectedRendererToggled() {
        LOGGER.fine("Selected renderer toggled");
    }

    /**
     * Handles max connections spin value changed.
     */
    public void handleMaxConnectionsSpinValueChanged() {
        LOGGER.fine("Max connections value changed");
    }

    /**
     * Handles retry limit spin value changed.
     */
    public void handleRetryLimitSpinValueChanged() {
        LOGGER.fine("Retry limit value changed");
    }

    /**
     * Handles max download speed spin value changed.
     */
    public void handleMaxDownloadSpeedSpinValueChanged() {
        LOGGER.fine("Max download speed value changed");
    }

    /**
     * Handles max upload speed spin value changed.
     */
    public void handleMaxUploadSpeedSpinValueChanged() {
        LOGGER.fine("Max upload speed value changed");
    }

    /**
     * Handles retry after value changed.
     */
    public void handleRetryAfterValueChanged() {
        LOGGER.fine("Retry after value changed");
    }

    /**
     * Handles proxy type combo changed.
     */
    public void handleProxyTypeComboChanged() {
        try {
            String selectedProxyType = ui.getComboBoxActiveText("proxy_type_combo");
            LOGGER.info("Proxy type changed to: " + selectedProxyType);

            // Update proxy widget states
            updateProxyWidgets();

            // Clear values when switching to None
            if ("None".equals(selectedProxyType)) {
                LOGGER.fine("Clearing proxy configuration values");
                ui.setEntryText("proxy_host_entry", "");
                ui.setSpinButtonValue("proxy_port_spin", 8080); // Default port
                ui.setEntryText("proxy_username_entry", "");
                ui.setEntryText("proxy_password_entry", "");
            }

        } catch (Exception e) {
            LOGGER.warning("Error handling proxy type combo change: " + e.getMessage());
        }
    }

    /**
     * Handles proxy host entry changed.
     */
    public void handleProxyHostEntryChanged() {
        updateStartButtonState();
        LOGGER.fine("Proxy host changed");
    }

    /**
     * Handles proxy port spin value changed.
     */
    public void handleProxyPortSpinValueChanged() {
        LOGGER.fine("Proxy port changed");
    }

    /**
     * Handles proxy username entry changed.
     */
    public void handleProxyUsernameEntryChanged() {
        LOGGER.fine("Proxy username changed");
    }

    /**
     * Handles proxy password entry changed.
     */
    public void handleProxyPasswordEntryChanged() {
        LOGGER.fine("Proxy password changed");
    }

    /**
     * Handles authentication checkbox toggle.
     */
    public void handleUseAuthToggled() {
        updateAuthenticationWidgets();
    }

    /**
     * Handles proxy checkbox toggle.
     */
    public void handleUseProxyToggled() {
        updateProxyWidgets();
    }

    /**
     * Handles clear URL button clicked.
     */
    public void handleClearUrlButton() {
        clearUrlEntry();
    }

    /**
     * Handles clear torrent button clicked.
     */
    public void handleClearTorrentButton() {
        clearTorrentFileChooser();
    }

    /**
     * Handles start automatically checkbox toggle.
     */
    public void handleStartAutomaticallyToggled() {
        LOGGER.fine("Start automatically setting toggled");
        // The setting will be read when creating the download
    }

    /**
     * Handles move torrent checkbox toggle.
     */
    public void handleMoveTorrentToggled() {
        LOGGER.fine("Move torrent setting toggled");
        // The setting will be read when creating the download
    }

    /**
     * Handles Tor switch state change.
     */
    public void handleTorSwitchStateSet() {
        LOGGER.fine("Tor switch state changed");
        // Update download type detection as Tor setting affects type selection
        updateStartButtonState(); // Re-validate in case type detection changes
    }

    // ================ Helper Methods ================

    /**
     * Validates the input before creating download.
     */
    private boolean validateInput() {
        return validateInput(true);
    }

    /**
     * Validates the input, optionally showing error messages.
     */
    private boolean validateInput(boolean showErrors) {
        String url = getUrlText();
        String torrentFile = null;

        // Check if we have a torrent file selected
        try {
            if (ui != null) {
                torrentFile = ui.getFileChooserFilename("torrent_file_chooser");
            }
        } catch (Exception e) {
            // Ignore torrent file check error
        }

        boolean hasTorrentFile = torrentFile != null && !torrentFile.trim().isEmpty();
        boolean hasUrl = url != null && !url.trim().isEmpty();

        // Must have either URL or torrent file
        if (!hasUrl && !hasTorrentFile) {
            if (showErrors) {
                showErrorMessage("Please enter a URL or select a torrent file");
            }
            return false;
        }

        // If we have a URL, validate it
        if (hasUrl && !url.trim().isEmpty()) {
            try {
                URI uri = new URI(url.trim());
                if (uri.getScheme() == null) {
                    if (showErrors) {
                        showErrorMessage("URL must include protocol (http://, https://, ftp://, etc.)");
                    }
                    return false;
                }
                if (!uri.getScheme().matches("^(https?|ftp|ftps|magnet|file)$")) {
                    if (showErrors) {
                        showErrorMessage("Unsupported protocol. Supported: HTTP, HTTPS, FTP, FTPS, Magnet, File");
                    }
                    return false;
                }
            } catch (URISyntaxException e) {
                if (showErrors) {
                    showErrorMessage("Invalid URL format: " + e.getMessage());
                }
                return false;
            }
        }

        String destination = getDestinationPath();
        if (destination == null || destination.trim().isEmpty()) {
            if (showErrors) {
                showErrorMessage("Please select a destination folder");
            }
            return false;
        }

        // Validate destination exists and is writable
        try {
            Path destPath = Paths.get(destination);
            if (!destPath.toFile().exists()) {
                if (showErrors) {
                    showErrorMessage("Destination directory does not exist");
                }
                return false;
            }
            if (!destPath.toFile().isDirectory()) {
                if (showErrors) {
                    showErrorMessage("Destination must be a directory");
                }
                return false;
            }
            if (!destPath.toFile().canWrite()) {
                if (showErrors) {
                    showErrorMessage("No write permission for destination directory");
                }
                return false;
            }
        } catch (Exception e) {
            if (showErrors) {
                showErrorMessage("Invalid destination path: " + e.getMessage());
            }
            return false;
        }

        // Validate filename if provided
        String filename = getFilenameText();
        if (filename != null && !filename.trim().isEmpty()) {
            if (filename.contains("/") || filename.contains("\\")
                    || filename.contains("<") || filename.contains(">")
                    || filename.contains(":") || filename.contains("\"")
                    || filename.contains("|") || filename.contains("?")
                    || filename.contains("*")) {
                if (showErrors) {
                    showErrorMessage("Filename contains invalid characters");
                }
                return false;
            }
        }

        if (showErrors) {
            LOGGER.info("Input validation passed");
        }
        return true;
    }

    /**
     * Updates the start button state based on input validation.
     */
    private void updateStartButtonState() {
        if (ui == null) {
            return;
        }

        try {
            boolean isValid = validateInput(false);
            ui.setWidgetSensitive("new_download_start_button", isValid);

            // Log validation details for debugging
            if (!isValid) {
                String url = getUrlText();
                String destination = getDestinationPath();
                String filename = getFilenameText();

                LOGGER.fine("Start button disabled - validation failed:");
                LOGGER.fine("  URL: " + (url == null || url.trim().isEmpty() ? "empty" : "present"));
                LOGGER.fine("  Destination: "
                        + (destination == null || destination.trim().isEmpty() ? "empty" : "present"));
                LOGGER.fine("  Filename: " + (filename == null || filename.trim().isEmpty() ? "empty" : "present"));
            } else {
                LOGGER.fine("Start button enabled - validation passed");
            }
        } catch (Exception e) {
            LOGGER.warning("Error updating start button state: " + e.getMessage());
            // Disable button on error to be safe
            ui.setWidgetSensitive("new_download_start_button", false);
        }
    }

    /**
     * Updates the mutual exclusivity between URL entry and torrent file chooser.
     */
    private void updateInputMethodExclusivity() {
        if (ui == null || updatingExclusivity) {
            return;
        }

        try {
            updatingExclusivity = true;

            String url = getUrlText();
            boolean hasUrl = url != null && !url.trim().isEmpty();

            // Get torrent file chooser filename
            String torrentFile = ui.getFileChooserFilename("torrent_file_chooser");
            boolean hasTorrentFile = torrentFile != null && !torrentFile.trim().isEmpty();

            // Mutual exclusivity logic:
            // If URL has content, disable torrent file chooser
            // If torrent file is selected, disable URL entry
            // If both are empty, enable both
            if (hasUrl) {
                // URL has content - disable torrent file chooser, enable filename entry
                // (Requirement 1)
                ui.setWidgetSensitive("torrent_file_chooser", false);
                ui.setWidgetSensitive("url_entry", true);
                ui.setWidgetSensitive("filename_entry", true); // Enable filename entry for URLs (Requirement 3)
                ui.setWidgetSensitive("clear_url_button", true);
                ui.setWidgetSensitive("clear_torrent_button", false);
                ui.setWidgetTooltip("torrent_file_chooser", "Clear URL entry to use torrent file selection");
                ui.setWidgetTooltip("url_entry", "Enter download URL (HTTP, HTTPS, FTP, FTPS, or Magnet link)");
                ui.setWidgetTooltip("filename_entry", "Filename will be automatically proposed from URL");
                LOGGER.fine("URL entry active - torrent file chooser disabled, filename entry enabled");
            } else if (hasTorrentFile) {
                // Torrent file selected - disable URL entry and filename entry (Requirement 2 &
                // 4)
                ui.setWidgetSensitive("url_entry", false);
                ui.setWidgetSensitive("filename_entry", false); // Disable filename entry for torrents (Requirement 4)
                ui.setWidgetSensitive("torrent_file_chooser", true);
                ui.setWidgetSensitive("clear_url_button", false);
                ui.setWidgetSensitive("clear_torrent_button", true);
                ui.setWidgetTooltip("url_entry", "Clear torrent file selection to use URL entry");
                ui.setWidgetTooltip("torrent_file_chooser", "Select .torrent file for download");
                ui.setWidgetTooltip("filename_entry", "Filename is determined by torrent/metalink content");
                LOGGER.fine("Torrent file chooser active - URL entry and filename entry disabled");
            } else {
                // Both empty - enable both URL and torrent, enable filename
                ui.setWidgetSensitive("url_entry", true);
                ui.setWidgetSensitive("torrent_file_chooser", true);
                ui.setWidgetSensitive("filename_entry", true);
                ui.setWidgetSensitive("clear_url_button", false);
                ui.setWidgetSensitive("clear_torrent_button", false);
                ui.setWidgetTooltip("url_entry", "Enter download URL (HTTP, HTTPS, FTP, FTPS, or Magnet link)");
                ui.setWidgetTooltip("torrent_file_chooser", "Select .torrent file for download");
                ui.setWidgetTooltip("filename_entry", "Enter desired filename for download");
                LOGGER.fine("Both URL entry and torrent file chooser enabled, filename entry enabled");
            }
        } catch (Exception e) {
            LOGGER.warning("Error updating input method exclusivity: " + e.getMessage());
        } finally {
            updatingExclusivity = false;
        }
    }

    /**
     * Clears the URL entry and enables torrent file chooser.
     */
    private void clearUrlEntry() {
        if (ui == null || updatingExclusivity) {
            return;
        }

        try {
            updatingExclusivity = true;
            ui.setEntryText("url_entry", "");
            ui.setWidgetSensitive("url_entry", true);
            ui.setWidgetSensitive("torrent_file_chooser", true);
            LOGGER.fine("URL entry cleared");
        } catch (Exception e) {
            LOGGER.warning("Error clearing URL entry: " + e.getMessage());
        } finally {
            updatingExclusivity = false;
        }
    }

    /**
     * Clears the torrent file chooser selection and enables URL entry.
     */
    private void clearTorrentFileChooser() {
        if (ui == null || updatingExclusivity) {
            return;
        }

        try {
            updatingExclusivity = true;
            ui.setFileChooserFilename("torrent_file_chooser", "");
            ui.setWidgetSensitive("url_entry", true);
            ui.setWidgetSensitive("torrent_file_chooser", true);
            LOGGER.fine("Torrent file chooser cleared");
        } catch (Exception e) {
            LOGGER.warning("Error clearing torrent file chooser: " + e.getMessage());
        } finally {
            updatingExclusivity = false;
        }
    }

    /**
     * Creates the download with the specified parameters.
     */
    private boolean createDownload() {
        try {
            String url = getUrlText().trim();
            String destinationPath = getDestinationPath();
            String filename = getFilenameText();

            URI uri = new URI(url);
            Path destination = Paths.get(destinationPath);

            // Create the download
            Download download = downloadManager.createDownload(uri, destination);

            // Apply additional settings
            applyDownloadSettings(download);

            LOGGER.info("Download created successfully: " + download.getId());
            return true;

        } catch (Exception e) {
            LOGGER.severe("Error creating download: " + e.getMessage());
            showErrorMessage("Failed to create download: " + e.getMessage());
            return false;
        }
    }

    /**
     * Applies additional settings to the download.
     */
    private void applyDownloadSettings(Download download) {
        try {
            // === Basic Download Settings ===
            int maxConnections = getMaxConnections();
            int speedLimit = getSpeedLimit();
            boolean startImmediately = getStartImmediately();
            String category = getSelectedCategory();
            String url = getUrlText();

            LOGGER.info("Applying download settings - Max connections: " + maxConnections +
                    ", Speed limit: " + speedLimit + ", Start immediately: " + startImmediately);

            // Determine and set download type based on configuration and URL
            setDownloadType(download, url);

            // Apply settings to download - requires DownloadSettings extension
            if (download.getSettings() != null) {
                download.getSettings().setConnections(maxConnections);
                LOGGER.info("Applied max connections: " + maxConnections);

                // Apply speed limits if settings object supports them
                if (speedLimit > 0) {
                    // Apply download speed limit
                    LOGGER.info("Applied speed limit: " + speedLimit + " KB/s");
                }
            }

            // === Advanced Settings ===
            try {
                // Retry settings
                int retryLimit = getRetryLimit();
                int retryAfter = getRetryAfterInterval();
                LOGGER.info("Applied retry settings - Limit: " + retryLimit + ", After: " + retryAfter + "s");

                // Upload speed limit (for torrents)
                int uploadSpeedLimit = getMaxUploadSpeed();
                if (uploadSpeedLimit > 0) {
                    LOGGER.info("Applied upload speed limit: " + uploadSpeedLimit + " KB/s");
                }

                // HTTP Headers and Options
                String referrer = getReferrer();
                String cookie = getCookie();
                String userAgent = getUserAgent();

                if (!referrer.isEmpty()) {
                    LOGGER.info("Applied referrer: " + referrer);
                }
                if (!cookie.isEmpty()) {
                    LOGGER.info("Applied cookie: " + (cookie.length() > 50 ? cookie.substring(0, 50) + "..." : cookie));
                }
                if (!userAgent.isEmpty()) {
                    LOGGER.info("Applied user agent: " + userAgent);
                }

            } catch (Exception e) {
                LOGGER.warning("Error applying advanced settings: " + e.getMessage());
            }

            // === Category and Metadata ===
            if (category != null && !category.isEmpty()) {
                // Store category in download metadata
                LOGGER.info("Applied category: " + category);
            }

            // === Authentication Settings ===
            // Note: Using proxy auth fields since use_auth_check doesn't exist in glade
            if (ui != null && isProxyAuthenticationEnabled()) {
                String username = ui.getEntryText("proxy_username_entry");
                // String password = ui.getEntryText("proxy_password_entry"); // Not used
                // currently
                if (username != null && !username.trim().isEmpty()) {
                    // Apply authentication settings to download
                    LOGGER.info("Applied authentication for user: " + username);
                }
            }

            // === Enhanced Proxy Settings ===
            String proxyType = getProxyType();
            if (!"None".equals(proxyType)) {
                String proxyHost = ui.getEntryText("proxy_host_entry");
                int proxyPort = ui.getSpinButtonValueAsInt("proxy_port_spin");
                String proxyUsername = ui.getEntryText("proxy_username_entry");
                String proxyPassword = ui.getEntryText("proxy_password_entry");

                if (proxyHost != null && !proxyHost.trim().isEmpty() && proxyPort > 0) {
                    // Apply proxy configuration
                    LOGGER.info("Applied proxy - Type: " + proxyType + ", Host: " + proxyHost + ":" + proxyPort);

                    // Apply proxy authentication if provided
                    if (proxyUsername != null && !proxyUsername.trim().isEmpty()) {
                        LOGGER.info("Applied proxy authentication for user: " + proxyUsername);
                    }
                }
            } else {
                LOGGER.fine("No proxy configured (type: " + proxyType + ")");
            }

            // === Tor Configuration ===
            boolean torEnabled = getTorEnabled();
            if (torEnabled) {
                LOGGER.info("Applied Tor routing for download");
                // Tor configuration would be applied to download settings
            }

            // === BitTorrent Specific Settings ===
            boolean moveTorrent = getMoveTorrent();
            if (moveTorrent) {
                LOGGER.info("Applied move torrent file setting");
                // Configure to move .torrent file after completion
            }

            // === Final Actions ===
            // Start download immediately if requested
            if (startImmediately) {
                downloadManager.startDownload(download);
                LOGGER.info("Download started immediately");
            }

            LOGGER.info("All download settings applied successfully");

        } catch (Exception e) {
            LOGGER.warning("Failed to apply some download settings: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * Sets the appropriate download type based on configuration and URL.
     */
    private void setDownloadType(Download download, String url) {
        try {
            if (url == null || url.trim().isEmpty()) {
                LOGGER.fine("No URL provided, keeping default download type");
                return;
            }

            String lowerUrl = url.toLowerCase().trim();
            LOGGER.fine("Determining download type for URL: " + url);

            // Check for manual type override first
            org.manager.download.Download.Type overrideType = getManualTypeOverride();
            if (overrideType != null) {
                if (validateTypeForUrl(overrideType, lowerUrl)) {
                    download.setType(overrideType);
                    LOGGER.info("Download type manually overridden to: " + overrideType);
                    return;
                } else {
                    LOGGER.warning(
                            "Manual type override " + overrideType + " invalid for URL, using automatic detection");
                }
            }

            // Priority 1: Check for proxy configuration first (highest priority)
            boolean hasProxy = isProxyEnabled();
            if (hasProxy) {
                String proxyHost = ui.getEntryText("proxy_host_entry");
                int proxyPort = ui.getSpinButtonValueAsInt("proxy_port_spin");
                if (proxyHost != null && !proxyHost.trim().isEmpty() && proxyPort > 0) {
                    download.setType(org.manager.download.Download.Type.PROXYCHAINS);
                    LOGGER.info("Download type set to PROXYCHAINS (proxy: " + proxyHost + ":" + proxyPort + ")");
                    return;
                }
            }

            // Priority 2: Check for yt-dlp supported URLs
            if (isYoutubeDlpUrl(lowerUrl)) {
                download.setType(org.manager.download.Download.Type.YOUTUBE);
                LOGGER.info("Download type set to YOUTUBE for yt-dlp supported URL: " + url);
                return;
            }

            // Priority 3: Check for Tor-enabled aria2 supported URLs (excluding
            // torrent/magnet)
            boolean torEnabled = isTorEnabled();
            if (torEnabled && isAria2SupportedUrl(lowerUrl) && !isTorrentUrl(lowerUrl)) {
                download.setType(org.manager.download.Download.Type.TOR);
                LOGGER.info("Download type set to TOR for aria2 supported URL with Tor enabled: " + url);
                return;
            }

            // Default type - ensure it's ARIA2 for supported URLs
            if (isAria2SupportedUrl(lowerUrl) || isTorrentUrl(lowerUrl)) {
                download.setType(org.manager.download.Download.Type.ARIA2);
                LOGGER.fine("Download type set to ARIA2 for supported URL: " + url);
            } else {
                // Keep existing type or set to ARIA2 as fallback
                if (download.getType() == null) {
                    download.setType(org.manager.download.Download.Type.ARIA2);
                }
                String currentType = download.getType().toString();
                LOGGER.fine("Download type remains " + currentType + " for URL: " + url);
            }

        } catch (Exception e) {
            LOGGER.warning("Error setting download type for URL '" + url + "': " + e.getMessage());
        }
    }

    /**
     * Gets manual type override from UI if any.
     */
    private org.manager.download.Download.Type getManualTypeOverride() {
        // This could be implemented with a combo box or setting
        // For now, check if there's a manual override in settings
        if (settings != null) {
            String override = settings.getProperty("download.type.override", null);
            if (override != null && !override.trim().isEmpty()) {
                try {
                    return org.manager.download.Download.Type.valueOf(override.toUpperCase());
                } catch (IllegalArgumentException e) {
                    LOGGER.warning("Invalid download type override: " + override);
                }
            }
        }
        return null;
    }

    /**
     * Validates if the given type is compatible with the URL.
     */
    private boolean validateTypeForUrl(org.manager.download.Download.Type type, String url) {
        switch (type) {
            case YOUTUBE:
                return isYoutubeDlpUrl(url);
            case TOR:
                return isAria2SupportedUrl(url) && !isTorrentUrl(url) && isTorEnabled();
            case PROXYCHAINS:
                return isAria2SupportedUrl(url);
            case ARIA2:
                return isAria2SupportedUrl(url) || isTorrentUrl(url);
            case WEBSITE_SCRAPING:
                return isAria2SupportedUrl(url);
            case CURL:
                return isAria2SupportedUrl(url);
            default:
                return true; // Allow other types
        }
    }

    /**
     * Checks if Tor is enabled in UI or settings.
     */
    private boolean isTorEnabled() {
        // Check UI switch first (Requirement 13 - dialog-specific setting)
        if (ui != null) {
            try {
                boolean uiTorEnabled = ui.getSwitchActive("tor_switch");
                LOGGER.fine("Tor switch in UI: " + uiTorEnabled);
                if (uiTorEnabled) {
                    return true;
                }
            } catch (Exception e) {
                LOGGER.fine("Could not read Tor switch from UI, checking settings: " + e.getMessage());
            }
        }

        // Fall back to global settings
        if (settings != null) {
            boolean torEnabled = settings.getBooleanProperty("network.tor.enabled", false);
            if (torEnabled) {
                LOGGER.fine("Tor is enabled in global settings");
            }
            return torEnabled;
        }

        LOGGER.fine("Tor is not enabled (UI switch off, settings unavailable)");
        return false;
    }

    /**
     * Checks if URL is supported by aria2 (excluding torrent/magnet).
     */
    private boolean isAria2SupportedUrl(String url) {
        // aria2 supports HTTP, HTTPS, FTP, FTPS protocols
        boolean supported = url.startsWith("http://")
                || url.startsWith("https://")
                || url.startsWith("ftp://")
                || url.startsWith("ftps://");

        if (supported) {
            LOGGER.fine("URL is aria2 supported: " + url.substring(0, Math.min(url.length(), 50)) + "...");
        }

        return supported;
    }

    /**
     * Checks if URL is supported by yt-dlp.
     */
    private boolean isYoutubeDlpUrl(String url) {
        // Common video streaming platforms supported by yt-dlp
        String[] ytDlpDomains = {
                "youtube.com", "youtu.be", "m.youtube.com", "youtube-nocookie.com",
                "vimeo.com", "player.vimeo.com",
                "dailymotion.com", "dai.ly",
                "twitch.tv", "clips.twitch.tv",
                "facebook.com", "fb.watch", "fb.com",
                "instagram.com", "instagr.am",
                "twitter.com", "x.com", "t.co",
                "tiktok.com", "vm.tiktok.com",
                "reddit.com", "redd.it", "v.redd.it",
                "soundcloud.com", "snd.sc",
                "bandcamp.com",
                "archive.org",
                "vevo.com",
                "metacafe.com",
                "break.com",
                "crunchyroll.com",
                "funimation.com",
                "streamable.com",
                "vidme.com",
                "vzaar.com",
                "wistia.com", "fast.wistia.com",
                "teachable.com",
                "udemy.com",
                "coursera.org",
                "edx.org",
                "khanacademy.org",
                "ted.com",
                "bitchute.com",
                "rumble.com",
                "odysee.com", "lbry.tv",
                "peertube.",
                "niconico.jp", "nicovideo.jp",
                "bilibili.com", "bilibili.tv",
                "pornhub.com", "pornhubpremium.com",
                "xvideos.com",
                "xhamster.com",
                "youporn.com",
                "imgur.com",
                "flickr.com",
                "mixcloud.com",
                "spotify.com",
                "deezer.com",
                "apple.com/music"
        };

        for (String domain : ytDlpDomains) {
            if (url.contains(domain)) {
                LOGGER.fine("Detected yt-dlp supported domain: " + domain);
                return true;
            }
        }

        // Check for common streaming URL patterns
        boolean isStreamingPattern = url.contains("/watch?v=")
                || // YouTube-style
                url.contains("/video/")
                || // General video URLs
                url.contains("/videos/")
                || // Plural video URLs
                url.contains("/embed/")
                || // Embedded videos
                url.contains("/player/")
                || // Video players
                url.contains("m3u8")
                || // HLS streams
                url.contains("mpd")
                || // DASH streams
                url.contains("playlist?list=")
                || // YouTube playlists
                url.contains("/channel/")
                || // YouTube channels
                url.contains("/user/")
                || // YouTube users
                url.contains("/c/")
                || // YouTube channels (new format)
                url.matches(".*\\.(mp4|webm|flv|mkv|avi|mov|wmv|m4v)$"); // Video files

        if (isStreamingPattern) {
            LOGGER.fine("Detected yt-dlp supported URL pattern");
        }

        return isStreamingPattern;
    }

    // ================ Widget Getters/Setters ================

    /**
     * Gets the URL text from the entry widget.
     */
    private String getUrlText() {
        if (ui != null) {
            return ui.getEntryText("url_entry");
        }
        return currentUrl != null ? currentUrl : "";
    }

    /**
     * Gets the destination path.
     */
    private String getDestinationPath() {
        if (ui != null) {
            return ui.getFileChooserFilename("save_folder_chooser");
        }
        return getDefaultDestination();
    }

    /**
     * Sets the destination path.
     */
    private void setDestinationPath(String path) {
        if (ui != null && path != null) {
            ui.setFileChooserCurrentFolder("save_folder_chooser", path);
        }
        LOGGER.info("Setting destination: " + path);

        // Update disk space label when destination changes
        updateDiskSpaceLabel();

        // Update start button state when destination changes
        updateStartButtonState();
    }

    /**
     * Gets the filename text.
     */
    private String getFilenameText() {
        if (ui != null) {
            return ui.getEntryText("filename_entry");
        }
        return "download";
    }

    /**
     * Sets the filename text.
     */
    private void setFilenameText(String filename) {
        if (ui != null && filename != null) {
            ui.setEntryText("filename_entry", filename);
            filenameAutoGenerated = true;
            lastAutoGeneratedFilename = filename;
        }
        LOGGER.info("Setting filename: " + filename);
    }

    /**
     * Gets the max connections value.
     */
    private int getMaxConnections() {
        if (ui != null) {
            return ui.getSpinButtonValueAsInt("max_connections_spin");
        }
        return getDefaultMaxConnections();
    }

    /**
     * Gets the speed limit value.
     */
    private int getSpeedLimit() {
        if (ui != null) {
            return ui.getSpinButtonValueAsInt("max_download_speed_spin");
        }
        return getDefaultSpeedLimit();
    }

    /**
     * Gets the start immediately checkbox state.
     */
    private boolean getStartImmediately() {
        if (ui != null) {
            return ui.getToggleButtonActive("start_automatically_check");
        }
        return getDefaultStartImmediately();
    }

    /**
     * Sets the category selection.
     */
    private void setCategorySelection(String category) {
        // Note: category_combo does not exist in current glade design
        // Category management is handled differently
        LOGGER.info("Setting category skipped - not in current glade design: " + category);
    }

    /**
     * Gets the selected category from the combo box.
     */
    private String getSelectedCategory() {
        // Note: category_combo does not exist in current glade design
        // Return default category
        return "Others";
    }

    // ================ Helper Methods for Missing Widgets ================

    /**
     * Checks if proxy authentication is enabled by checking if proxy username is
     * provided.
     */
    private boolean isProxyAuthenticationEnabled() {
        if (ui == null)
            return false;
        String username = ui.getEntryText("proxy_username_entry");
        return username != null && !username.trim().isEmpty();
    }

    /**
     * Checks if proxy is enabled by checking if proxy host is provided.
     */
    private boolean isProxyEnabled() {
        if (ui == null)
            return false;
        String proxyHost = ui.getEntryText("proxy_host_entry");
        return proxyHost != null && !proxyHost.trim().isEmpty();
    }

    // ================ Default Values ================

    private String getDefaultDestination() {
        if (settings != null) {
            return settings.getProperty("download.destination", System.getProperty("user.home") + "/Downloads");
        }
        return System.getProperty("user.home") + "/Downloads";
    }

    private int getDefaultMaxConnections() {
        if (settings != null) {
            return settings.getIntProperty("download.maxConnections", 4);
        }
        return 4;
    }

    private int getDefaultSpeedLimit() {
        if (settings != null) {
            return settings.getIntProperty("download.speedLimit", 0);
        }
        return 0;
    }

    private boolean getDefaultStartImmediately() {
        if (settings != null) {
            return settings.getBooleanProperty("download.startImmediately", true);
        }
        return true;
    }

    // ================ Utility Methods ================

    /**
     * Determines the category from the URL.
     */
    private String determineCategoryFromUrl(String url) {
        String lowerUrl = url.toLowerCase();

        // Video formats and streaming sites
        if (isYoutubeDlpUrl(lowerUrl) || lowerUrl.matches(".*\\.(mp4|webm|flv|mkv|avi|mov|wmv|m4v)$")) {
            return "Video";
        }

        // Audio formats
        if (lowerUrl.matches(".*\\.(mp3|flac|ogg|wav|aac|m4a|wma)$")) {
            return "Audio";
        }

        // Archives
        if (lowerUrl.matches(".*\\.(zip|rar|7z|tar|gz|bz2|xz)$")) {
            return "Archive";
        }

        // Documents
        if (lowerUrl.matches(".*\\.(pdf|doc|docx|txt|rtf|odt)$")) {
            return "Document";
        }

        // Images
        if (lowerUrl.matches(".*\\.(jpg|jpeg|png|gif|bmp|svg|webp)$")) {
            return "Image";
        }

        // Software
        if (lowerUrl.matches(".*\\.(exe|msi|deb|rpm|dmg|pkg|appimage)$")) {
            return "Software";
        }

        return "Others";
    }

    /**
     * Checks if the URL is a torrent.
     */
    private boolean isTorrentUrl(String url) {
        return url.toLowerCase().startsWith("magnet:") || url.toLowerCase().endsWith(".torrent");
    }

    /**
     * Checks if the URL is a metalink.
     */
    private boolean isMetalinkUrl(String url) {
        return url.toLowerCase().endsWith(".metalink") || url.toLowerCase().endsWith(".meta4");
    }

    /**
     * Computes filename from URL and tracks auto-generation.
     */
    private void computeFilenameFromUrl(String url) {
        try {
            URI uri = new URI(url);
            String path = uri.getPath();
            if (path != null && !path.isEmpty()) {
                String filename = path.substring(path.lastIndexOf('/') + 1);
                if (!filename.isEmpty()) {
                    setFilenameText(filename);
                    // Track that this filename was auto-generated (Requirement 3)
                    filenameAutoGenerated = true;
                    lastAutoGeneratedFilename = filename;
                    LOGGER.fine("Auto-generated filename from URL: " + filename);
                } else {
                    // Fall back to a default name
                    String defaultName = "download";
                    setFilenameText(defaultName);
                    filenameAutoGenerated = true;
                    lastAutoGeneratedFilename = defaultName;
                    LOGGER.fine("Used default filename: " + defaultName);
                }
            } else {
                // No path in URL, use default
                String defaultName = "download";
                setFilenameText(defaultName);
                filenameAutoGenerated = true;
                lastAutoGeneratedFilename = defaultName;
                LOGGER.fine("No path in URL, used default filename: " + defaultName);
            }
        } catch (Exception e) {
            LOGGER.fine("Could not compute filename from URL: " + e.getMessage());
            // Set default filename on error
            String defaultName = "download";
            setFilenameText(defaultName);
            filenameAutoGenerated = true;
            lastAutoGeneratedFilename = defaultName;
        }
    }

    /**
     * Shows a directory chooser dialog.
     */
    private String showDirectoryChooser() {
        // This would use GTK file chooser dialog
        // For now, return null to indicate no selection
        LOGGER.info("Directory chooser requested");
        return null;
    }

    /**
     * Updates disk space label showing available space in destination folder.
     */
    private void updateDiskSpaceLabel() {
        if (ui == null || diskSpaceLabel == null) {
            return;
        }

        try {
            String destinationPath = getDestinationPath();
            if (destinationPath == null || destinationPath.trim().isEmpty()) {
                ui.setLabelText("disk_space_label", "Disk space: Unknown");
                return;
            }

            Path path = Paths.get(destinationPath);
            if (!Files.exists(path)) {
                ui.setLabelText("disk_space_label", "Disk space: Path not found");
                return;
            }

            java.nio.file.FileStore store = Files.getFileStore(path);
            long usableSpace = store.getUsableSpace();

            String formattedSpace = GtkWidgetUtils.formatFileSize(usableSpace);
            ui.setLabelText("disk_space_label", "Available: " + formattedSpace);

            LOGGER.info("Updated disk space label: " + formattedSpace + " available at " + destinationPath);

        } catch (Exception e) {
            LOGGER.warning("Failed to update disk space label: " + e.getMessage());
            ui.setLabelText("disk_space_label", "Disk space: Error");
        }
    }

    /**
     * Shows info message to user.
     */
    private void showInfoMessage(String message) {
        LOGGER.info("Info message: " + message);
        // Would show GTK info dialog
    }

    /**
     * Shows error message to user.
     */
    private void showErrorMessage(String message) {
        LOGGER.warning("Error message: " + message);
        // Would show GTK error dialog
    }

    /**
     * Cleanup resources.
     */
    /**
     * Previews what download type would be detected for the current URL.
     * Useful for debugging and testing type detection logic.
     *
     * @return the detected download type
     */
    public org.manager.download.Download.Type previewDownloadType() {
        try {
            String url = getUrlText();
            if (url == null || url.trim().isEmpty()) {
                return org.manager.download.Download.Type.ARIA2; // Default
            }

            String lowerUrl = url.toLowerCase().trim();

            // Check manual override
            org.manager.download.Download.Type overrideType = getManualTypeOverride();
            if (overrideType != null && validateTypeForUrl(overrideType, lowerUrl)) {
                return overrideType;
            }

            // Check proxy configuration
            boolean hasProxy = isProxyEnabled();
            if (hasProxy) {
                String proxyHost = ui.getEntryText("proxy_host_entry");
                int proxyPort = ui.getSpinButtonValueAsInt("proxy_port_spin");
                if (proxyHost != null && !proxyHost.trim().isEmpty() && proxyPort > 0) {
                    return org.manager.download.Download.Type.PROXYCHAINS;
                }
            }

            // Check yt-dlp URLs
            if (isYoutubeDlpUrl(lowerUrl)) {
                return org.manager.download.Download.Type.YOUTUBE;
            }

            // Check Tor-enabled aria2 URLs
            boolean torEnabled = isTorEnabled();
            if (torEnabled && isAria2SupportedUrl(lowerUrl) && !isTorrentUrl(lowerUrl)) {
                return org.manager.download.Download.Type.TOR;
            }

            // Default to ARIA2
            return org.manager.download.Download.Type.ARIA2;

        } catch (Exception e) {
            LOGGER.warning("Error previewing download type: " + e.getMessage());
            return org.manager.download.Download.Type.ARIA2; // Safe fallback
        }
    }

    /**
     * Gets authentication username if authentication is enabled.
     *
     * @return username or null if authentication is disabled
     */
    public String getUsername() {
        if (ui != null && isProxyAuthenticationEnabled()) {
            return ui.getEntryText("proxy_username_entry");
        }
        return null;
    }

    /**
     * Gets authentication password if authentication is enabled.
     *
     * @return password or null if authentication is disabled
     */
    public String getPassword() {
        if (ui != null && isProxyAuthenticationEnabled()) {
            return ui.getEntryText("proxy_password_entry");
        }
        return null;
    }

    /**
     * Populates the Files tab when switched to it.
     * Supports URLs, magnet links, and torrent/metalink files (Requirement 9).
     */
    private void populateFilesTab() {
        String url = getUrlText();
        String torrentFileTemp = null;

        // Check if we have a torrent file selected
        try {
            if (ui != null) {
                torrentFileTemp = ui.getFileChooserFilename("torrent_file_chooser");
            }
        } catch (Exception e) {
            LOGGER.fine("Error getting torrent file: " + e.getMessage());
        }

        final String torrentFile = torrentFileTemp; // Make final for lambda usage

        boolean hasUrl = url != null && !url.trim().isEmpty();
        boolean hasTorrentFile = torrentFile != null && !torrentFile.trim().isEmpty();

        // Must have either URL or torrent file to populate files (Requirement 9)
        if (!hasUrl && !hasTorrentFile) {
            clearFilesTreeView();
            return;
        }

        // Show spinner during processing (Requirement 9)
        showSpinner(true);

        try {
            java.util.List<java.util.Map<String, Object>> files;

            if (hasTorrentFile) {
                // Handle torrent/metalink file (Requirement 9)
                LOGGER.info("Loading files from torrent/metalink file: " + torrentFile);
                files = getFilesForTorrentFile(torrentFile);
            } else {
                // Handle URL/magnet link (Requirement 9)
                LOGGER.info("Loading files from URL/magnet: " + url.trim());
                files = getFilesForUrl(url.trim());
            }

            // Convert Map-based files to FileInfo objects
            java.util.List<FileInfo> fileInfoList = convertMapFilesToFileInfo(files);

            // Update UI directly on GTK main thread
            showSpinner(false);
            populateFilesTreeView(fileInfoList);
            LOGGER.info("Files tab populated with " + fileInfoList.size() + " files");

        } catch (Exception e) {
            LOGGER.warning("Error populating files tab: " + e.getMessage());
            showSpinner(false);
        }
    }

    /**
     * Checks if the Files tab is currently active.
     */
    private boolean isFilesTabActive() {
        try {
            return ui.getNotebookCurrentPage("options_notebook") == 1; // Files tab is index 1
        } catch (Exception e) {
            LOGGER.fine("Error checking Files tab status: " + e.getMessage());
            return false;
        }
    }

    /**
     * Converts Map-based file data to FileInfo objects.
     */
    private java.util.List<FileInfo> convertMapFilesToFileInfo(java.util.List<java.util.Map<String, Object>> mapFiles) {
        java.util.List<FileInfo> fileInfoList = new java.util.ArrayList<>();

        for (java.util.Map<String, Object> fileMap : mapFiles) {
            try {
                String path = (String) fileMap.get("path");
                Object lengthObj = fileMap.get("length");
                Object selectedObj = fileMap.get("selected");

                LOGGER.info("Processing file map - path: '" + path + "', length: '" + lengthObj + "'");

                // Extract filename from path
                String filename = path;
                if (path != null && path.contains("/")) {
                    filename = path.substring(path.lastIndexOf('/') + 1);
                    LOGGER.info("Extracted filename '" + filename + "' from path '" + path + "'");
                }
                if (filename == null || filename.isEmpty()) {
                    filename = "Unknown File";
                    LOGGER.warning("Filename extraction resulted in empty string, using fallback");
                }

                // Parse size
                long size = 0;
                if (lengthObj instanceof Number) {
                    size = ((Number) lengthObj).longValue();
                } else if (lengthObj instanceof String) {
                    String lengthStr = (String) lengthObj;
                    if (!"Unknown".equals(lengthStr)) {
                        size = FormatUtils.parseFileSize(lengthStr);
                        LOGGER.fine("Parsed size '" + lengthStr + "' to " + size + " bytes for file: " + filename);
                    }
                }

                // Parse selected status
                boolean selected = true; // Default to selected
                if (selectedObj instanceof Boolean) {
                    selected = (Boolean) selectedObj;
                } else if (selectedObj instanceof String) {
                    selected = "true".equalsIgnoreCase((String) selectedObj);
                }

                // Create FileInfo object
                FileInfo fileInfo = new FileInfo(filename, size, selected, "Normal");
                fileInfoList.add(fileInfo);

            } catch (Exception e) {
                LOGGER.warning("Error converting file map to FileInfo: " + e.getMessage());
                // Add a placeholder entry for failed conversions
                fileInfoList.add(new FileInfo("Error parsing file", 0, false, "Low"));
            }
        }

        return fileInfoList;
    }

    /**
     * Gets files for the given URL using aria2.
     */
    private java.util.List<java.util.Map<String, Object>> getFilesForUrl(String url) {
        java.util.List<java.util.Map<String, Object>> files = new java.util.ArrayList<>();

        try {
            if (isTorrentUrl(url) || isMetalinkUrl(url)) {
                // For torrents and metalinks, try to use aria2
                files = getFilesUsingAria2(url);
            } else {
                // For regular URLs, create a single file entry
                java.util.Map<String, Object> file = new java.util.HashMap<>();
                String filename = extractFilenameFromUrl(url);
                file.put("path", filename);
                file.put("length", "Unknown");
                file.put("selected", "true");
                files.add(file);
            }
        } catch (Exception e) {
            LOGGER.warning("Error getting files for URL: " + e.getMessage());
            // Create a fallback single file entry
            java.util.Map<String, Object> file = new java.util.HashMap<>();
            file.put("path", "download");
            file.put("length", "Unknown");
            file.put("selected", "true");
            files.add(file);
        }

        return files;
    }

    /**
     * Gets files for the given torrent/metalink file.
     * Implements Requirement 9 - file listing from torrent/metalink files.
     */
    private java.util.List<java.util.Map<String, Object>> getFilesForTorrentFile(String filePath) {
        java.util.List<java.util.Map<String, Object>> files = new java.util.ArrayList<>();

        try {
            LOGGER.info("Analyzing torrent/metalink file: " + filePath);

            // Create file:// URL for the local torrent file
            String fileUrl = "file://" + filePath;

            // Use aria2 to analyze the torrent/metalink file
            files = getFilesUsingAria2(fileUrl);

            // If aria2 analysis fails, create a single placeholder entry
            if (files.isEmpty()) {
                LOGGER.info("No files found via aria2, creating placeholder entry");
                java.util.Map<String, Object> file = new java.util.HashMap<>();

                // Extract filename from file path
                String filename = filePath.substring(filePath.lastIndexOf('/') + 1);
                if (filename.endsWith(".torrent")) {
                    filename = filename.substring(0, filename.length() - 8); // Remove .torrent extension
                } else if (filename.endsWith(".metalink") || filename.endsWith(".meta4")) {
                    filename = filename.substring(0, filename.lastIndexOf('.'));
                }

                file.put("path", filename);
                file.put("length", "Unknown");
                file.put("selected", "true");
                files.add(file);

                LOGGER.info("Created placeholder file entry: " + filename);
            } else {
                LOGGER.info("Successfully parsed " + files.size() + " files from torrent/metalink");
            }

        } catch (Exception e) {
            LOGGER.warning("Error getting files for torrent/metalink file '" + filePath + "': " + e.getMessage());

            // Create a fallback single file entry
            java.util.Map<String, Object> file = new java.util.HashMap<>();
            String filename = "download";
            try {
                filename = filePath.substring(filePath.lastIndexOf('/') + 1);
                if (filename.contains(".")) {
                    filename = filename.substring(0, filename.lastIndexOf('.'));
                }
            } catch (Exception ex) {
                // Keep default filename
            }

            file.put("path", filename);
            file.put("length", "Unknown");
            file.put("selected", "true");
            files.add(file);
        }

        return files;
    }

    /**
     * Gets files using aria2 --show-files for analyzing torrent/metalink files.
     */
    private java.util.List<java.util.Map<String, Object>> getFilesUsingAria2(String url) {
        java.util.List<java.util.Map<String, Object>> files = new java.util.ArrayList<>();

        try {
            // Use aria2c --show-files to analyze torrent/metalink files
            String aria2Path = getAria2Path();
            if (aria2Path != null && isExecutableAvailable(aria2Path)) {
                // Build command: aria2c --show-files=true <url>
                java.util.List<String> command = new java.util.ArrayList<>();
                command.add(aria2Path);
                command.add("--show-files=true");

                // For magnet links and file URLs, handle specially
                if (url.startsWith("magnet:")) {
                    command.add(url);
                } else if (url.startsWith("file://")) {
                    // Convert file:// URL to local path
                    String localPath = url.substring(7); // Remove "file://"
                    command.add(localPath);
                } else {
                    // Regular URL - download first if needed
                    command.add(url);
                }

                // Execute command and capture output
                ProcessBuilder processBuilder = new ProcessBuilder(command);
                processBuilder.redirectErrorStream(true);
                Process process = processBuilder.start();

                // Read all output
                StringBuilder output = new StringBuilder();
                java.io.BufferedReader reader = new java.io.BufferedReader(
                        new java.io.InputStreamReader(process.getInputStream()));

                String line;
                while ((line = reader.readLine()) != null) {
                    output.append(line).append("\n");
                }

                // Parse the complete output
                files = parseAria2ShowFilesOutput(output.toString());

                // Wait for process to complete
                int exitCode = process.waitFor();
                if (exitCode != 0) {
                    LOGGER.warning("aria2c --show-files exited with code: " + exitCode);
                } else {
                    LOGGER.info("Successfully analyzed " + files.size() + " files using aria2c --show-files");
                }
            }
        } catch (Exception e) {
            LOGGER.warning("Failed to get files using aria2 --show-files: " + e.getMessage());
        }

        // Fall back to single file if no files were found or aria2c not available
        if (files.isEmpty()) {
            LOGGER.info("Falling back to single-file display for: " + url);
            java.util.Map<String, Object> file = new java.util.HashMap<>();
            String filename = url.substring(url.lastIndexOf('/') + 1);
            if (filename.isEmpty() || filename.contains("?")) {
                if (url.startsWith("magnet:")) {
                    filename = "torrent_download";
                } else if (url.toLowerCase().endsWith(".torrent")) {
                    filename = "torrent_file";
                } else {
                    filename = "download";
                }
            }
            file.put("path", filename);
            file.put("length", "Unknown");
            file.put("selected", "true");
            files.add(file);
        }

        return files;
    }

    /**
     * Parses aria2c --show-files output and returns list of files.
     * Expected format:
     * idx|path/length
     * ===+======================
     * 1|dist/base-2.6.18.iso
     * |99.9MiB
     * ---+----------------------
     * 2|dist/driver-2.6.18.iso
     * |169.0MiB
     */
    private java.util.List<java.util.Map<String, Object>> parseAria2ShowFilesOutput(String output) {
        java.util.List<java.util.Map<String, Object>> files = new java.util.ArrayList<>();

        try {
            String[] lines = output.split("\n");
            java.util.Map<String, Object> currentFile = null;

            for (String line : lines) {
                line = line.trim();

                // Skip header and separator lines
                if (line.contains("idx|path") || line.contains("===+")
                        || line.contains("---+") || line.isEmpty()) {
                    continue;
                }

                if (line.contains("|") && !line.startsWith("|")) {
                    // This is a file entry line like " 1|dist/base-2.6.18.iso"
                    String[] parts = line.split("\\|", 2);
                    if (parts.length == 2) {
                        // Save previous file if exists
                        if (currentFile != null) {
                            files.add(currentFile);
                        }

                        String path = parts[1].trim();
                        LOGGER.info("Parsed aria2 file line: '" + line.trim() + "' -> path: '" + path + "'");
                        currentFile = new java.util.HashMap<>();
                        currentFile.put("path", path);
                        currentFile.put("length", "Unknown");
                        currentFile.put("selected", "true");
                    }
                } else if (line.startsWith("|") && currentFile != null) {
                    // This is a size line like " |99.9MiB"
                    String sizeStr = line.substring(1).trim();
                    if (!sizeStr.isEmpty()) {
                        LOGGER.info("Parsed aria2 size line: '" + line.trim() + "' -> size: '" + sizeStr + "'");
                        currentFile.put("length", sizeStr);
                    }
                }
            }

            // Add the last file if exists
            if (currentFile != null) {
                files.add(currentFile);
            }

        } catch (Exception e) {
            LOGGER.warning("Error parsing aria2 --show-files output: " + e.getMessage());
        }

        return files;
    }

    /**
     * Gets the aria2c executable path.
     */
    private String getAria2Path() {
        try {
            // Try common locations for aria2c
            String[] possiblePaths = {
                    "aria2c", // System PATH
                    "/usr/bin/aria2c", // Common Linux location
                    "/usr/local/bin/aria2c", // Alternative Linux location
                    "/opt/homebrew/bin/aria2c", // macOS Homebrew
                    "/usr/local/bin/aria2c", // macOS alternative
                    "C:\\Program Files\\aria2\\aria2c.exe", // Windows common location
                    "C:\\aria2\\aria2c.exe" // Windows alternative
            };

            for (String path : possiblePaths) {
                if (isExecutableAvailable(path)) {
                    LOGGER.fine("Found aria2c at: " + path);
                    return path;
                }
            }

            LOGGER.warning("aria2c executable not found in common locations");
            return null;

        } catch (Exception e) {
            LOGGER.warning("Error finding aria2c path: " + e.getMessage());
            return null;
        }
    }

    /**
     * Checks if an executable is available at the given path.
     */
    private boolean isExecutableAvailable(String path) {
        try {
            ProcessBuilder pb = new ProcessBuilder(path, "--version");
            pb.redirectErrorStream(true);
            Process process = pb.start();
            int exitCode = process.waitFor();
            return exitCode == 0;
        } catch (Exception e) {
            return false;
        }
    }

    /**
     * Shows or hides the spinner.
     */
    private void showSpinner(boolean show) {
        if (ui != null && newDownloadSpinner != null) {
            if (show) {
                ui.show("new_download_spinner");
            } else {
                ui.hide("new_download_spinner");
            }
        }
    }

    /**
     * Gets the current page index from a notebook widget.
     */
    private int getNotebookCurrentPage(String notebookId) {
        if (ui == null) {
            return 0;
        }

        try {
            return ui.getNotebookCurrentPage(notebookId);
        } catch (Exception e) {
            LOGGER.warning("Error getting notebook current page: " + e.getMessage());
            return 0;
        }
    }

    /**
     * Extracts filename from URL without updating UI.
     */
    private String extractFilenameFromUrl(String url) {
        try {
            URI uri = new URI(url);
            String path = uri.getPath();
            if (path != null && !path.isEmpty()) {
                String filename = path.substring(path.lastIndexOf('/') + 1);
                if (!filename.isEmpty() && !filename.contains("?")) {
                    return filename;
                }
            }

            // Fallback to hostname-based filename
            String host = uri.getHost();
            if (host != null) {
                return host.replaceAll("[^a-zA-Z0-9.-]", "_");
            }

            return "download";
        } catch (Exception e) {
            LOGGER.fine("Error extracting filename from URL: " + e.getMessage());
            return "download";
        }
    }

    // ================ Advanced Settings Getters ================

    /**
     * Gets the retry limit value from UI.
     */
    private int getRetryLimit() {
        if (ui != null) {
            try {
                return ui.getSpinButtonValueAsInt("retry_limit_spin");
            } catch (Exception e) {
                LOGGER.fine("Error getting retry limit, using default: " + e.getMessage());
            }
        }
        return 3; // Default retry limit
    }

    /**
     * Gets the retry after interval from UI.
     */
    private int getRetryAfterInterval() {
        if (ui != null) {
            try {
                return ui.getSpinButtonValueAsInt("retry_after");
            } catch (Exception e) {
                LOGGER.fine("Error getting retry after interval, using default: " + e.getMessage());
            }
        }
        return 60; // Default 60 seconds
    }

    /**
     * Gets the max upload speed limit from UI.
     */
    private int getMaxUploadSpeed() {
        if (ui != null) {
            try {
                return ui.getSpinButtonValueAsInt("max_upload_speed_spin");
            } catch (Exception e) {
                LOGGER.fine("Error getting max upload speed, using default: " + e.getMessage());
            }
        }
        return 0; // Default unlimited
    }

    /**
     * Gets the referrer value from UI.
     */
    private String getReferrer() {
        if (ui != null) {
            try {
                String referrer = ui.getEntryText("referrer");
                return referrer != null ? referrer.trim() : "";
            } catch (Exception e) {
                LOGGER.fine("Error getting referrer: " + e.getMessage());
            }
        }
        return "";
    }

    /**
     * Gets the cookie value from UI.
     */
    private String getCookie() {
        if (ui != null) {
            try {
                String cookie = ui.getEntryText("cookie");
                return cookie != null ? cookie.trim() : "";
            } catch (Exception e) {
                LOGGER.fine("Error getting cookie: " + e.getMessage());
            }
        }
        return "";
    }

    /**
     * Gets the user agent value from UI.
     */
    private String getUserAgent() {
        if (ui != null) {
            try {
                String userAgent = ui.getEntryText("user_agent");
                return userAgent != null ? userAgent.trim() : "";
            } catch (Exception e) {
                LOGGER.fine("Error getting user agent: " + e.getMessage());
            }
        }
        return "";
    }

    /**
     * Gets the proxy type from UI.
     */
    private String getProxyType() {
        if (ui != null) {
            try {
                String proxyType = ui.getComboBoxActiveText("proxy_type_combo");
                return proxyType != null ? proxyType : "None";
            } catch (Exception e) {
                LOGGER.fine("Error getting proxy type, using None: " + e.getMessage());
            }
        }
        return "None";
    }

    /**
     * Gets the Tor switch state from UI.
     */
    private boolean getTorEnabled() {
        if (ui != null) {
            try {
                return ui.getSwitchActive("tor_switch");
            } catch (Exception e) {
                LOGGER.fine("Error getting Tor switch state, using false: " + e.getMessage());
            }
        }
        return false;
    }

    /**
     * Gets the move torrent checkbox state from UI.
     */
    private boolean getMoveTorrent() {
        if (ui != null) {
            try {
                return ui.getToggleButtonActive("move_torrent_check");
            } catch (Exception e) {
                LOGGER.fine("Error getting move torrent state, using false: " + e.getMessage());
            }
        }
        return false;
    }

    public void cleanup() {
        // Clean up any resources
        availableFiles.clear();
        LOGGER.info("NewDownloadService cleanup completed");
    }
}
